### PR TITLE
Gui and tray updates

### PR DESCRIPTION
**Pull request by tvoverbeek**
See commit message for commit 7f48244

### CODE REVIEW

**Comment by hp1337** [comment]
Thanks for all the fixes! I'm having one issue when using pijuice_cli.py and selecting "Wakeup Alarm" option:

  File "/usr/bin/pijuice_cli.py", line 1258, in item_chosen
    callback()
  File "/usr/bin/pijuice_cli.py", line 1045, in __init__
    self.device_time = self._get_device_time()
  File "/usr/bin/pijuice_cli.py", line 1114, in _get_device_time
    str(t['second']).rjust(2, '0')))
  File "/usr/bin/pijuice_cli.py", line 1120, in _update_status
    self.status_text.set_text("Status: " + self.status)
AttributeError: 'WakeupAlarmTab' object has no attribute 'status_text'

Any idea why that may be?

**Comment by tvoverbeek** [comment]
@hp1337 Have reproduced the error. Working at a fix.

**Comment by tvoverbeek** [comment]
@hp1337 Fixed now, please test.

**Comment by hp1337** [comment]
@tvoverbeek Its fixed now thanks!

**Pull request merged**
