### PR TITLE
Pijuice external software halt, power off

### PR DESCRIPTION
**Pull request by codejedi365**
This feature addition adds a system task flag and adjustable delay control for power off of the pijuice module.  This modification is similar to the SYS_FUNC_HALT_POW_OFF system function where power is supplied for 60 seconds after a system halt is sent to the Raspberry Pi.  The variance here is that the pijuice_sys.py script detects any halt, shutdown, or poweroff issued by any other software external to pijuice actions (SSH, GNOME desktop, etc) and will provide power for a delay after shutdown command.  The delay is provided in seconds and the clock starts when the 'pijuice.service stop' is issued by systemd during shutdown.

Reboot is ignored and any other pijuice module/software generated effects occur as configured by user.  This is possible since the script verifies the existence of systemd target's such as reboot.target.*start and shutdown.target.*start.

This is a great supplement for users who are already using the SYS_FUNC_HALT_POW_OFF function for their button actions but also have the possibility of using SSH to remotely shutdown the device for a full power off.

The Software Readme has been updated to reflect how to use this function and below is the image to replace the screenshot of the System Task Settings Menu.

Updated Image to include. (No similar way for me to upload image until now, see url below)
System Task Menu Screenshot

### CODE REVIEW

**Comment by tvoverbeek** [comment]
@codejedi365 Did you get it to work?
I am testing it but it does not work for me.
I am using my 'pijuice-separate-normal-user' branch with python3.5
The stop option in pijuice-sys main() gets called properly, but sometime when trying to execute
the subprocess call it is terminated, so the power off time never gets set.
When I manually stop the pijuice-service the subprocess call is executed.
My guess is since you are in shutdown no new processes are allowed, or the just created subprocess gets killed.

**Comment by codejedi365** [comment]
@tvoverbeek, yes I did get it to work on two different images (Octopi & Rasbian) with a 30, 60, 70 second delay test runs. I was not using the 'pijuice-separate-normal-user' branch nor the python3.5 since the default apt-get install puts it into python2.7 dist-packages. 

I am currently reverting and will perform another test install and a python3.5 run to rule out any inconsistencies. 

I'm not familiar with the 'pijuice-separate-normal-user' branch's intent but as a guess if it is running it at a user level then systemctl will fail.  systemctl command will need to be run with root privileges which is how my installation of pijuice.service was installed.

**Comment by codejedi365** [comment]
@tvoverbeek, I now see what you were experiencing.  Subprocess.check_output was changed in Python3.3/3.4 to output byte-like data rather than a string as it was in python2.7.  Also, python3 was more picky about the tab spacing which I have now fixed. 

I ran the test with both python2.7 and python3.5 so pijuice_sys.py is compatible with both versions.  I read up on the 'pijuice-separate-normal-user' branch and its a great step towards security.  I take back what I mentioned before about needing root permissions since that is not the case for 'systemctl list-jobs' therefore I don't believe it will have any effect on the operation of this feature.  Disclaimer though, I did not test this feature on the branch.

**Comment by tvoverbeek** [comment]
@codejedi365 Turns out that 'systemctl list jobs' has to be run as root to get the desired output when shutting down.
One remaining problem is the 'isHalting' flag. This is set in the main process of pijuice_sys.py.
The 'stop' code is executed after the main process is killed (ExecStopPost clause in the service file).
This starts a new copy of pijuice_sys.py which has its own copy of pijuice.py -> isHalting is always False when the 'stop' is executed.
You can verify this by setting the external delay to e.g. 30 sec and doing a button shutdown (provided it executes SYS_FUNC_HALT_POW_OFF) then the power will go after after 30 seconds, not after 60 seconds as coded in the ExecuteFunc() for the SYS_FUNC_HALT_POW_OFF case.
The initial SetPowerOff(60) is superseded by the SetPowerOff(30) in the 'pijuice_sys.py stop' process.
Any idea how to communicate this from the main service process to the 'pijuice_sys.py stop' one running afterward?
Via a file in /tmp?

**Comment by tvoverbeek** [comment]
@codejedi365
First, I think this is a very good feature to add to the pijuice software. Should have mentioned it in my first comment to this PR.

I found a simple way to communicate the isHalting state between the main pijuice_sys process and the one executing 'pijuice_sys.py stop' which runs after the main pijuice_sys is killed.

In _SystemHalt() create a file in /tmp (similar to touch):
```
    pijuice.status.SetLedBlink('D2', 3, [150, 0, 0], 200, [0, 100, 0], 200)
    # Setting halt flag for 'pijuice_sys.py stop'
    with open(HALT_FILE, 'w') as f:
        pass
    subprocess.call(["sudo", "halt"])
```
In the 'stop' branch of main():
```
    if len(sys.argv) > 1 and str(sys.argv[1]) == 'stop':
        isHalting = False
        if os.path.exists(HALT_FILE):   # Created in _SystemHalt() called in main pijuice_sys process
            isHalting = True
            os.remove(HALT_FILE)
```
and the big if further dowb becomes:
```
        ret = pijuice.status.GetStatus()
        if ( ret['error'] == 'NO_ERROR'
            and not isHalting
            and causePowerOff                                # proper time to power down (!rebooting)
            and configData.get('system_task',{}).get('ext_halt_power_off', {}).get('enabled',False)
            ):
```
The SetHaltFlag() in pijuice.py is not needed then.

Tested with this logic and it works like it should.

Could you modify your PR with these changes, then I can merge it.

**Comment by codejedi365** [comment]
@tvoverbeek Oh thanks! I'm glad you agree.  I saw your first message but I have had competing priorities this week and was unable to test the changes in the new branch.  I do think the /tmp file is a good implementation, now that there is two separate processes requiring communication.  I will make your suggested changes over the weekend.  

For clarification, you would be merging this branch into the 'pijuice-separate-normal-use' branch correct?  Do you need me to create a separate PR for this or are you able to change the destination of this PR?

Lastly, I think your second comment about superseding SetPowerOff() brings to light another question on how we should add in this feature.  It is best explained in this example:

_Say I configure the SYS_FUNC_HALT_POW_OFF to a button press (currently means 60 seconds hardcoded), then configure this feature Software Halt Power Off which has a user-configurable # of seconds (set to 30).  Should it remain independent from one another even though it accomplishes the same task of shutdown?_

My vote:  leave it separate for now and potentially merge the two for the user's sake in a future enhancement.

**Comment by tvoverbeek** [comment]
@codejedi365 Regarding the power-off delay for SYS_FUNC_HALT_POW_OFF, I would leave it alone for now.
Will be on holiday until Oct 12. Propose you keep your PR for the main branch. I will add it to my separate user branch manually.

**Comment by codejedi365** [comment]
@tvoverbeek Great! Thanks for the response! I have added and tested the discussed code changes above so it should be good to go.  Enjoy your vacation!

**Pull request merged**
