### PR TITLE
Utiltity to dump configuration and mass load on another unit

### PR DESCRIPTION
**Pull request by tilghman**

### CODE REVIEW

**Comment by shawaj** [comment]
This relates to #496 and possibly #88

**Comment by shawaj** [comment]
@tilghman would you be able to write up some text about this script and what it is used for etc etc for the readme? It would be very useful to have that

**Comment by shawaj** [comment]
@tvoverbeek do you think this looks ok?

@tilghman any update on usage instructions / documentation?

**Comment by tilghman** [comment]
The basic intent of the script is to be able to dump the settings to a file on one system, then load those same settings into a new PiJuice.

So, for example:

pijuice_util.py --dump > dumpfile.js
pijuice_util.py --load < dumpfile.js

**Comment by shawaj** [comment]
And these functions as well?

```
    g.add_argument('--enable-wakeup', action='store_true', help='enable the wakeup flag')
    g.add_argument('--get-time', action='store_true', help='print(the RTC time')
    g.add_argument('--get-alarm', action='store_true', help='print(the RTC alarm')
    g.add_argument('--get-status', action='store_true', help='print(the pijiuce status')
    g.add_argument('--get-config', action='store_true', help='print(the pijiuce config')
    g.add_argument('--get-battery', action='store_true', help='print(the pijiuce battery status')
    g.add_argument('--get-input', action='store_true', help='print(the pijiuce input status')
```

**Comment by tilghman** [comment]
I think I used those for debugging.  The mass dump and mass load functions are what I'm using.

**Comment by shawaj** [comment]
@tilghman sure, but do these work to do what they say they do? If so, I'll add them to documentation as well

**Comment by tilghman** [comment]
They're basically just copied out of the other tool, so... yes?

**Comment by shawaj** [comment]
@tvoverbeek sounds good to me re moving to different directory.

**Comment by tvoverbeek** [comment]
Merged. Thanks @tilghman

**Comment by shawaj** [comment]
Thanks @tilghman @tvoverbeek

**Comment by tilghman** [comment]
Happy to be able to contribute.  Thanks @shawaj @tvoverbeek

**Pull request merged**
